name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Application
        run: dotnet run --project ./ManagementPersoane.csproj
        env:
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false

      - name: Verify Generated Files
        run: |
          ls -la
          if [ -f index.html ]; then echo "index.html exists"; else echo "index.html missing"; exit 1; fi
          if [ -f persoane.json ]; then echo "persoane.json exists"; else echo "persoane.json missing"; exit 1; fi
          if [ -f raport.txt ]; then echo "raport.txt exists"; else echo "raport.txt missing"; exit 1; fi

      - name: Setup Pages
        uses: actions/configure-pages@v5
       
